import { defineConfig } from "vite";
import { resolve } from "path";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import react from "@vitejs/plugin-react";

const API_URLS = {
  dev:  "http://localhost:8000",
  prod: "https://api.contxtly.xyz",
};

function copyStaticFiles() {
  return {
    name: "copy-static-files",
    closeBundle() {
      const dist = resolve(__dirname, "dist");

      // Copy manifest
      copyFileSync(
        resolve(__dirname, "manifest.json"),
        resolve(dist, "manifest.json")
      );

      // Copy content CSS
      if (!existsSync(resolve(dist, "styles"))) {
        mkdirSync(resolve(dist, "styles"));
      }
      copyFileSync(
        resolve(__dirname, "styles/content.css"),
        resolve(dist, "styles/content.css")
      );

      // Copy popup HTML (JS + CSS are now generated by Vite/Tailwind)
      if (!existsSync(resolve(dist, "popup"))) {
        mkdirSync(resolve(dist, "popup"));
      }
      copyFileSync(
        resolve(__dirname, "src/popup/popup.html"),
        resolve(dist, "popup/popup.html")
      );

      // Copy extension icons
      if (!existsSync(resolve(dist, "icons"))) {
        mkdirSync(resolve(dist, "icons"));
      }
      for (const size of [16, 32, 48, 128]) {
        copyFileSync(
          resolve(__dirname, `icons/icon-${size}.png`),
          resolve(dist, `icons/icon-${size}.png`)
        );
      }
    },
  };
}

export default defineConfig(({ mode }) => ({
  plugins: [react(), copyStaticFiles()],
  define: {
    "import.meta.env.VITE_API_URL": JSON.stringify(API_URLS[mode] ?? API_URLS.dev),
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        content: resolve(__dirname, "src/content/content.js"),
        background: resolve(__dirname, "src/background.js"),
        popup: resolve(__dirname, "src/app/main.tsx"),
      },
      output: {
        entryFileNames: (chunkInfo) => {
          if (chunkInfo.name === "popup") return "popup/popup.js";
          if (chunkInfo.name === "content") return "content/content.js";
          return "[name].js";
        },
        chunkFileNames: "popup/chunks/[name]-[hash].js",
        assetFileNames: (assetInfo) => {
          if (assetInfo.name?.endsWith(".css")) return "popup/popup.css";
          return "assets/[name]-[hash][extname]";
        },
      },
    },
  },
}));
