"""In-memory store for the German dictionaries.

Loaded from SQLite at app startup via load(). The file path is set by
the GERMAN_SQLITE_PATH env var; missing file is a hard error. The file
is generated by backend/scripts/build_german_sqlite.py and shipped
alongside the backend.

Public state (mutated in place by load()):
    NOMEN_VERB                       dict[(noun, verb_lemma) -> canonical]
    NOMEN_VERB_PREP                  dict[(prep, noun, verb_lemma) -> canonical]
    NOMEN_VERB_REFLEXIVE             set[(noun, verb_lemma)]
    NOMEN_VERB_PREP_REFLEXIVE        dict[(prep, noun, verb_lemma) -> canonical]
    NOMEN_VERB_INDEX                 dict[noun_lower -> list[(noun, verb_lemma)]]
    NOMEN_VERB_PREP_INDEX            dict[noun_lower -> list[(prep, noun, verb)]]
    NOMEN_VERB_PREP_REFLEXIVE_INDEX  dict[noun_lower -> list[(prep, noun, verb)]]
    FIXED_EXPRESSIONS                dict[tuple[str, ...] -> canonical]
    EXPRESSION_INDEX                 dict[word_lower -> list[tuple[str, ...]]]
    FIGURATIVE_EXPRESSIONS           set[tuple[str, ...]]
    EXPRESSION_MEANINGS              dict[tuple[str, ...] -> {meaning_de, meaning_targets}]
    VERB_PREPOSITION_COLLOCATIONS    dict[(verb_lemma, prep) -> pattern]
"""

import json
import logging
import os
import sqlite3
from pathlib import Path

log = logging.getLogger(__name__)

SQLITE_PATH_ENV = "GERMAN_SQLITE_PATH"

# Public state — mutated in place by loaders
NOMEN_VERB: dict[tuple[str, str], str] = {}
NOMEN_VERB_PREP: dict[tuple[str, str, str], str] = {}
NOMEN_VERB_REFLEXIVE: set[tuple[str, str]] = set()
NOMEN_VERB_PREP_REFLEXIVE: dict[tuple[str, str, str], str] = {}
NOMEN_VERB_INDEX: dict[str, list[tuple[str, str]]] = {}
NOMEN_VERB_PREP_INDEX: dict[str, list[tuple[str, str, str]]] = {}
NOMEN_VERB_PREP_REFLEXIVE_INDEX: dict[str, list[tuple[str, str, str]]] = {}

FIXED_EXPRESSIONS: dict[tuple[str, ...], str] = {}
EXPRESSION_INDEX: dict[str, list[tuple[str, ...]]] = {}

# Tokens-key → metadata for figurative entries (idioms from Wiktionary).
# Empty for plain fixed expressions. Used by the response layer to mark
# idioms and surface paraphrases.
FIGURATIVE_EXPRESSIONS: set[tuple[str, ...]] = set()
EXPRESSION_MEANINGS: dict[tuple[str, ...], dict] = {}  # tokens → {meaning_de, meaning_targets}

VERB_PREPOSITION_COLLOCATIONS: dict[tuple[str, str], str] = {}

# Modal particles (Modalpartikeln). Keyed on (particle_lower, sentence_type)
# where sentence_type ∈ {'declarative', 'interrogative', 'imperative'}. Value
# is the pragmatic reading shown to the translator/UI.
MODAL_PARTICLES: dict[tuple[str, str], str] = {}

# Lower-cased set of every German noun lemma we know about (from the
# german_noun table seeded from Wiktionary). Used by the v2 compound
# splitter to:
#   - skip the splitter entirely when the input is already a known noun
#   - prefer noun candidates over verb candidates when cleaning Fugen-
#     stripped parts (so "Eil" stays "Eil"/"Eile" rather than becoming
#     the verb "eilen" via simplemma)
GERMAN_NOUN_LEMMAS: set[str] = set()

# Closed list of weak masculine nouns following the n-Deklination
# pattern (Mensch → Menschen, Student → Studenten). Loaded from the
# german_n_decl table; lemmas stored capitalised as in the dict.
N_DECL_LEMMAS: set[str] = set()


def _build_indexes() -> None:
    """Rebuild the reverse indexes from the primary dicts."""
    NOMEN_VERB_INDEX.clear()
    for (noun, verb_lemma) in NOMEN_VERB:
        NOMEN_VERB_INDEX.setdefault(noun.lower(), []).append((noun, verb_lemma))

    NOMEN_VERB_PREP_INDEX.clear()
    for (prep, noun, verb_lemma) in NOMEN_VERB_PREP:
        NOMEN_VERB_PREP_INDEX.setdefault(noun.lower(), []).append((prep, noun, verb_lemma))

    NOMEN_VERB_PREP_REFLEXIVE_INDEX.clear()
    for (prep, noun, verb_lemma) in NOMEN_VERB_PREP_REFLEXIVE:
        NOMEN_VERB_PREP_REFLEXIVE_INDEX.setdefault(noun.lower(), []).append((prep, noun, verb_lemma))

    EXPRESSION_INDEX.clear()
    for tokens in FIXED_EXPRESSIONS:
        for word in tokens:
            EXPRESSION_INDEX.setdefault(word.lower(), []).append(tokens)


def _fetch_sqlite(path: Path) -> dict:
    """Read every dictionary table from a local SQLite file.

    Array/jsonb columns were JSON-encoded into TEXT by the build script;
    decode them back. SQLite booleans (stored as ints) become bools.
    """
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row

    def _q(sql: str, json_cols: tuple[str, ...] = ()) -> list[dict]:
        out = []
        for r in conn.execute(sql).fetchall():
            d = dict(r)
            for col in json_cols:
                v = d.get(col)
                if isinstance(v, str):
                    d[col] = json.loads(v) if v else None
            if "requires_sich" in d:
                d["requires_sich"] = bool(d["requires_sich"])
            if "figurative" in d:
                d["figurative"] = bool(d["figurative"])
            out.append(d)
        return out

    try:
        return {
            "nvv": _q("select noun, verb_lemma, prep_lemma, canonical, requires_sich from german_nvv"),
            "expr": _q(
                "select tokens, canonical, figurative, meaning_de, meaning_targets from german_expression",
                json_cols=("tokens", "meaning_targets"),
            ),
            "coll": _q("select verb_lemma, preposition, pattern from german_collocation"),
            "particle": _q("select particle, sentence_type, reading from german_modal_particle"),
            "noun": _q("select lemma from german_noun"),
            "n_decl": _q("select lemma from german_n_decl"),
        }
    finally:
        conn.close()


def load() -> None:
    """Load the German dictionaries from SQLite into memory.

    Hard-requires GERMAN_SQLITE_PATH to be set and the file to exist —
    we no longer fall back to Supabase.
    """
    sqlite_path_str = os.environ.get(SQLITE_PATH_ENV, "").strip()
    if not sqlite_path_str:
        raise RuntimeError(f"{SQLITE_PATH_ENV} is not set")
    sqlite_path = Path(sqlite_path_str)
    if not sqlite_path.exists():
        raise RuntimeError(f"{SQLITE_PATH_ENV}={sqlite_path} but file does not exist")

    log.info("Loading German dicts from %s", sqlite_path)
    rows = _fetch_sqlite(sqlite_path)
    source_label = sqlite_path.name

    nvv_rows      = rows["nvv"]
    expr_rows     = rows["expr"]
    coll_rows     = rows["coll"]
    particle_rows = rows["particle"]
    noun_rows     = rows["noun"]
    n_decl_rows   = rows["n_decl"]

    if not nvv_rows or not expr_rows or not coll_rows:
        raise RuntimeError(
            f"Empty result for one or more German dictionaries "
            f"(nvv={len(nvv_rows)}, expr={len(expr_rows)}, coll={len(coll_rows)}) "
            f"from {source_label}."
        )

    NOMEN_VERB.clear()
    NOMEN_VERB_PREP.clear()
    NOMEN_VERB_REFLEXIVE.clear()
    NOMEN_VERB_PREP_REFLEXIVE.clear()

    for r in nvv_rows:
        noun = r["noun"]
        verb_lemma = r["verb_lemma"]
        prep_lemma = r["prep_lemma"]
        canonical = r["canonical"]
        requires_sich = r["requires_sich"]

        if prep_lemma is None:
            NOMEN_VERB[(noun, verb_lemma)] = canonical
            if requires_sich:
                NOMEN_VERB_REFLEXIVE.add((noun, verb_lemma))
        elif requires_sich:
            NOMEN_VERB_PREP_REFLEXIVE[(prep_lemma, noun, verb_lemma)] = canonical
        else:
            NOMEN_VERB_PREP[(prep_lemma, noun, verb_lemma)] = canonical

    FIXED_EXPRESSIONS.clear()
    FIGURATIVE_EXPRESSIONS.clear()
    EXPRESSION_MEANINGS.clear()
    for r in expr_rows:
        tokens = tuple(r["tokens"])
        FIXED_EXPRESSIONS[tokens] = r["canonical"]
        if r.get("figurative"):
            FIGURATIVE_EXPRESSIONS.add(tokens)
        meaning_de = r.get("meaning_de")
        meaning_targets = r.get("meaning_targets")
        if meaning_de or meaning_targets:
            EXPRESSION_MEANINGS[tokens] = {
                "meaning_de": meaning_de,
                "meaning_targets": meaning_targets,
            }

    VERB_PREPOSITION_COLLOCATIONS.clear()
    for r in coll_rows:
        VERB_PREPOSITION_COLLOCATIONS[(r["verb_lemma"], r["preposition"])] = r["pattern"]

    MODAL_PARTICLES.clear()
    for r in particle_rows:
        MODAL_PARTICLES[(r["particle"].lower(), r["sentence_type"])] = r["reading"]

    GERMAN_NOUN_LEMMAS.clear()
    for r in noun_rows:
        lemma = (r.get("lemma") or "").strip()
        if lemma:
            GERMAN_NOUN_LEMMAS.add(lemma.lower())

    N_DECL_LEMMAS.clear()
    for r in n_decl_rows:
        lemma = (r.get("lemma") or "").strip()
        if lemma:
            N_DECL_LEMMAS.add(lemma)

    _build_indexes()

    log.info(
        "Loaded German dicts from %s: %d NVV / %d NVV+prep / %d NVV+prep+sich / "
        "%d expressions (%d figurative) / %d collocations / %d modal particles / "
        "%d noun lemmas / %d n-Dekl",
        source_label,
        len(NOMEN_VERB), len(NOMEN_VERB_PREP), len(NOMEN_VERB_PREP_REFLEXIVE),
        len(FIXED_EXPRESSIONS), len(FIGURATIVE_EXPRESSIONS),
        len(VERB_PREPOSITION_COLLOCATIONS), len(MODAL_PARTICLES),
        len(GERMAN_NOUN_LEMMAS), len(N_DECL_LEMMAS),
    )
